[package]
name = "rust-tradier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.30"
reqwest = "0.12.2"
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["io-util", "rt"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
